In [14]:
import pandas as pd

In [16]:
df = pd.read_csv("records.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'records.csv'

In [17]:
df.sort_values(["Country"],axis=0, ascending=[True],inplace=True)
df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
50,Europe,Albania,Clothes,Online,C,2/2/2010,385383069,3/18/2010,2269,109.28,35.84,247956.32,81320.96,166635.36
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
32,Australia and Oceania,Australia,Office Supplies,Online,C,10/27/2015,158535134,11/25/2015,2924,651.21,524.96,1904138.04,1534983.04,369155.00
60,Australia and Oceania,Australia,Cereal,Offline,H,6/9/2013,450563752,7/2/2013,682,205.70,117.11,140287.40,79869.02,60418.38
91,Australia and Oceania,Australia,Beverages,Offline,H,7/7/2014,240470397,7/11/2014,9389,47.45,31.79,445508.05,298476.31,147031.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Asia,Turkmenistan,Office Supplies,Online,M,4/23/2013,462405812,5/20/2013,5010,651.21,524.96,3262562.10,2630049.60,632512.50
18,Asia,Turkmenistan,Household,Offline,L,12/30/2010,441619336,1/20/2011,3830,668.27,502.54,2559474.10,1924728.20,634745.90
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
58,Europe,United Kingdom,Household,Online,L,1/5/2012,955357205,2/14/2012,282,668.27,502.54,188452.14,141716.28,46735.86
83,Sub-Saharan Africa,Zambia,Snacks,Online,L,1/4/2011,122583663,1/5/2011,4085,152.58,97.44,623289.30,398042.40,225246.90

In [18]:
df.T

,50,6,32,60,91,57,92,41,12,67,...,36,42,87,29,37,70,18,0,58,83
Region,Europe,Sub-Saharan Africa,Australia and Oceania,Australia and Oceania,Australia and Oceania,Europe,Middle East and North Africa,Middle East and North Africa,Asia,Central America and the Caribbean,...,Middle East and North Africa,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa,Sub-Saharan Africa,Asia,Asia,Australia and Oceania,Europe,Sub-Saharan Africa
Country,Albania,Angola,Australia,Australia,Australia,Austria,Azerbaijan,Azerbaijan,Bangladesh,Belize,...,Syria,The Gambia,The Gambia,The Gambia,The Gambia,Turkmenistan,Turkmenistan,Tuvalu,United Kingdom,Zambia
Item Type,Clothes,Household,Office Supplies,Cereal,Beverages,Cosmetics,Office Supplies,Cosmetics,Clothes,Clothes,...,Fruits,Cereal,Baby Food,Household,Meat,Office Supplies,Household,Baby Food,Household,Snacks
Sales Channel,Online,Offline,Online,Offline,Offline,Offline,Online,Online,Online,Offline,...,Online,Offline,Offline,Offline,Online,Online,Offline,Offline,Online,Online
Order Priority,C,M,C,H,H,H,M,M,L,M,...,L,H,M,L,M,M,L,H,L,L
Order Date,2/2/2010,4/23/2011,10/27/2015,6/9/2013,7/7/2014,2/23/2015,6/13/2012,2/6/2010,1/13/2017,7/25/2016,...,11/22/2011,6/7/2012,2/3/2014,5/26/2012,1/14/2017,4/23/2013,12/30/2010,5/28/2010,1/5/2012,1/4/2011
Order ID,385383069,135425221,158535134,450563752,240470397,868214595,423331391,382392299,187310731,807025039,...,162052476,994022214,494747245,886494815,825304400,462405812,441619336,669165933,955357205,122583663
Ship Date,3/18/2010,4/27/2011,11/25/2015,7/2/2013,7/11/2014,3/2/2015,7/24/2012,2/25/2010,3/1/2017,9/7/2016,...,12/3/2011,6/8/2012,3/20/2014,6/9/2012,1/23/2017,5/20/2013,1/20/2011,6/27/2010,2/14/2012,1/5/2011
Units Sold,2269,4187,2924,682,9389,2847,2021,7234,8263,5498,...,3784,2117,5559,2370,4767,5010,3830,9925,282,4085
Unit Price,109.28,668.27,651.21,205.7,47.45,437.2,651.21,437.2,109.28,109.28,...,9.33,205.7,255.28,668.27,421.89,651.21,668.27,255.28,668.27,152.58
Unit Cost,35.84,502.54,524.96,117.11,31.79,263.33,524.96,263.33,35.84,35.84,...,6.92,117.11,159.42,502.54,364.69,524.96,502.54,159.42,502.54,97.44
Total Revenue,247956.32,2798046.49,1904138.04,140287.4,445508.05,1244708.4,1316095.41,3162704.8,902980.64,600821.44,...,35304.72,435466.9,1419101.52,1583799.9,2011149.63,3262562.1,2559474.1,2533654.0,188452.14,623289.3
Total Cost,81320.96,2104134.98,1534983.04,79869.02,298476.31,749700.51,1060944.16,1904929.22,296145.92,197048.32,...,26185.28,247921.87,886215.78,1191019.8,1738477.23,2630049.6,1924728.2,1582243.5,141716.28,398042.4
Total Profit,166635.36,693911.51,369155.0,60418.38,147031.74,495007.89,255151.25,1257775.58,606834.72,403773.12,...,9119.44,187545.03,532885.74,392780.1,272672.4,632512.5,634745.9,951410.5,46735.86,225246.9

In [19]:
df.shape

(100, 14)

In [20]:
df.size

1400